# Generated by Django 5.1 on 2024-10-30 01:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0007_remove_book_entry_date_remove_book_purchase_location'),
        ('common', '0002_alter_purchaselocation_business_number_and_more'),
        ('students', '0004_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='입고 수량')),
                ('received_date', models.DateField(verbose_name='입고 날짜')),
                ('list_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='정가')),
                ('unit_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='단가')),
                ('selling_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='판매가')),
                ('distribution_target', models.TextField(blank=True, null=True, verbose_name='지급대상')),
                ('distribution_date', models.DateField(blank=True, null=True, verbose_name='지급 날짜')),
                ('return_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='반품 권수')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='반품 날짜')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='참고')),
                ('spare1', models.CharField(blank=True, max_length=200, null=True, verbose_name='예비1')),
                ('spare2', models.CharField(blank=True, max_length=200, null=True, verbose_name='예비2')),
                ('spare3', models.CharField(blank=True, max_length=200, null=True, verbose_name='예비3')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book', verbose_name='도서명')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student', verbose_name='지급 학생')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.subject', verbose_name='과목')),
            ],
            options={
                'verbose_name': '교재 재고',
                'verbose_name_plural': '교재 재고 관리',
            },
        ),
    ]
