# Generated by Django 5.1 on 2024-10-30 04:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_inventory', '0003_alter_bookdistribution_options_and_more'),
        ('common', '0002_alter_purchaselocation_business_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookdistribution',
            options={'ordering': ['-distribution_date'], 'verbose_name': '교재 지급', 'verbose_name_plural': '교재 지급 관리'},
        ),
        migrations.AlterModelOptions(
            name='bookstock',
            options={'ordering': ['-received_date'], 'verbose_name': '교재 입고', 'verbose_name_plural': '교재 입고 관리'},
        ),
        migrations.RemoveField(
            model_name='bookstock',
            name='spare1',
        ),
        migrations.RemoveField(
            model_name='bookstock',
            name='spare2',
        ),
        migrations.RemoveField(
            model_name='bookstock',
            name='spare3',
        ),
        migrations.AddField(
            model_name='bookstock',
            name='order_status',
            field=models.CharField(choices=[('IN_STOCK', '재고충분'), ('LOW_STOCK', '재고부족'), ('OUT_OF_STOCK', '재고없음'), ('ON_ORDER', '주문중')], default='IN_STOCK', max_length=20, verbose_name='재고상태'),
        ),
        migrations.AddField(
            model_name='bookstock',
            name='purchase_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.purchaselocation', verbose_name='구매처'),
        ),
        migrations.AddField(
            model_name='bookstock',
            name='reorder_point',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='재주문 기준수량'),
        ),
        migrations.AlterField(
            model_name='bookstock',
            name='quantity_received',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='수량'),
        ),
        migrations.CreateModel(
            name='BookStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', '입고'), ('OUT', '출고'), ('RETURN', '반품'), ('LOSS', '분실/파손'), ('ADJUST', '재고조정')], max_length=10, verbose_name='거래 유형')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='처리일시')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('book_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_inventory.bookstock', verbose_name='교재')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
            ],
            options={
                'verbose_name': '재고 변동 이력',
                'verbose_name_plural': '재고 변동 이력 관리',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
