# Generated by Django 5.1 on 2024-10-13 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='교재명')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('difficulty', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='교재 난이도')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='원가')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='입고가격')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='판매가격')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.publisher', verbose_name='출판사')),
                ('purchase_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.purchaselocation', verbose_name='구입처')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.subject', verbose_name='과목')),
            ],
            options={
                'verbose_name': '교재',
                'verbose_name_plural': '교재',
            },
        ),
        migrations.CreateModel(
            name='TextbookInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('date', models.DateField(verbose_name='입고/출고일')),
                ('is_incoming', models.BooleanField(verbose_name='입고 여부')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textbooks.textbook', verbose_name='교재')),
            ],
            options={
                'verbose_name': '교재 재고',
                'verbose_name_plural': '교재 재고',
            },
        ),
        migrations.CreateModel(
            name='TextbookQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(max_length=20, verbose_name='문제 고유번호')),
                ('category_large', models.CharField(max_length=100, verbose_name='대분류')),
                ('category_medium', models.CharField(max_length=100, verbose_name='중분류')),
                ('category_small', models.CharField(max_length=100, verbose_name='소분류')),
                ('question_type', models.CharField(max_length=50, verbose_name='유형번호')),
                ('difficulty', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='문제 난이도')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textbooks.textbook', verbose_name='교재')),
            ],
            options={
                'verbose_name': '교재 문항',
                'verbose_name_plural': '교재 문항',
                'unique_together': {('textbook', 'question_number')},
            },
        ),
    ]
