# Generated by Django 5.1 on 2024-10-13 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('student_id', models.CharField(max_length=6, unique=True, verbose_name='학생 고유번호')),
                ('grade', models.CharField(choices=[('K5', 'K5'), ('K6', 'K6'), ('K7', 'K7'), ('K8', 'K8'), ('K9', 'K9'), ('K10', 'K10'), ('K11', 'K11'), ('K12', 'K12')], max_length=3, verbose_name='학년')),
                ('phone', models.CharField(max_length=15, verbose_name='전화번호')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여')], max_length=1, verbose_name='성별')),
                ('parent_phone', models.CharField(max_length=15, verbose_name='부모님 전화번호')),
                ('cash_receipt_number', models.CharField(max_length=20, verbose_name='현금영수증용 번호')),
                ('interview_date', models.DateField(verbose_name='인터뷰 날짜')),
                ('first_class_date', models.DateField(verbose_name='첫수업 날짜')),
                ('last_class_date', models.DateField(blank=True, null=True, verbose_name='그만 둔 날짜')),
                ('interview_score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='상담시 성적')),
                ('base_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_students', to='classes.class', verbose_name='기본 학급')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': '학생',
                'verbose_name_plural': '학생',
            },
        ),
    ]
