# Generated by Django 5.1 on 2024-10-13 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cash_receipt_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='현금영수증용 번호'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_class_date',
            field=models.DateField(null=True, verbose_name='첫수업 날짜'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남'), ('F', '여')], max_length=1, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, choices=[('K5', 'K5'), ('K6', 'K6'), ('K7', 'K7'), ('K8', 'K8'), ('K9', 'K9'), ('K10', 'K10'), ('K11', 'K11'), ('K12', 'K12')], max_length=3, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='student',
            name='interview_date',
            field=models.DateField(null=True, verbose_name='인터뷰 날짜'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='부모님 전화번호'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.school', verbose_name='학교'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(editable=False, max_length=8, unique=True, verbose_name='학생 고유번호'),
        ),
    ]
