# Generated by Django 5.1 on 2024-10-18 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_base_class_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '학생', 'verbose_name_plural': '학생들'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_class_date',
            new_name='quit_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='base_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cash_receipt_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AddField(
            model_name='student',
            name='etc',
            field=models.TextField(blank=True, null=True, verbose_name='기타'),
        ),
        migrations.AddField(
            model_name='student',
            name='extra1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='예비1'),
        ),
        migrations.AddField(
            model_name='student',
            name='extra2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='예비2'),
        ),
        migrations.AddField(
            model_name='student',
            name='extra3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='예비3'),
        ),
        migrations.AddField(
            model_name='student',
            name='extra4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='예비4'),
        ),
        migrations.AddField(
            model_name='student',
            name='extra5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='예비5'),
        ),
        migrations.AddField(
            model_name='student',
            name='interview_info',
            field=models.TextField(blank=True, null=True, verbose_name='인터뷰 정보'),
        ),
        migrations.AddField(
            model_name='student',
            name='personal_file',
            field=models.FileField(blank=True, null=True, upload_to='student_files/', verbose_name='개인 파일'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='형식: 000-0000-0000', regex='^\\d{3}-\\d{3,4}-\\d{4}$')], verbose_name='학생 전화번호'),
        ),
        migrations.AddField(
            model_name='student',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='현금영수증용 번호'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일 주소'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남'), ('F', '여')], max_length=1, null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, choices=[('K5', 'K5'), ('K6', 'K6'), ('K7', 'K7'), ('K8', 'K8'), ('K9', 'K9'), ('K10', 'K10'), ('K11', 'K11'), ('K12', 'K12')], max_length=3, null=True, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='student',
            name='interview_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='인터뷰 기본 성적'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='형식: 000-0000-0000', regex='^\\d{3}-\\d{3,4}-\\d{4}$')], verbose_name='부모님 전화번호'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=8, unique=True, verbose_name='학생 고유번호'),
        ),
    ]
