# Generated by Django 4.2.16 on 2024-11-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '학생', 'verbose_name_plural': '학생'},
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=8, unique=True, verbose_name='고유번호'),
        ),
    ]
