# Generated by Django 4.2.16 on 2024-11-14 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_options_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_files/', verbose_name='파일')),
                ('file_name', models.CharField(max_length=255, verbose_name='파일명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 날짜')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='students.student')),
            ],
            options={
                'verbose_name': '학생 파일',
                'verbose_name_plural': '학생 파일',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
