# Generated by Django 4.2.16 on 2024-11-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentfile'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='student',
        #     name='is_active',
        #     field=models.BooleanField(default=True, verbose_name='활동 여부'),
        # ),
    ]
