# Generated by Django 5.1 on 2024-10-13 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('teachers', '0001_initial'),
        ('textbooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='수업명')),
                ('day', models.IntegerField(choices=[(0, '일'), (1, '월'), (2, '화'), (3, '수'), (4, '목'), (5, '금'), (6, '토')], verbose_name='수업 요일')),
                ('time', models.IntegerField(choices=[(10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00')], verbose_name='수업 시간')),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='수강료')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.subject', verbose_name='과목')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='담당교사')),
                ('textbook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='textbooks.textbook', verbose_name='교재')),
            ],
            options={
                'verbose_name': '수업',
                'verbose_name_plural': '수업',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(verbose_name='등록일')),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class', verbose_name='수업')),
            ],
            options={
                'verbose_name': '수강신청',
                'verbose_name_plural': '수강신청',
            },
        ),
    ]
