# Generated by Django 5.1 on 2024-10-13 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='학생'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'class_instance')},
        ),
    ]
