# Generated by Django 5.1 on 2024-10-13 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('textbooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(verbose_name='분석일')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='총점')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='학생')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textbooks.textbook', verbose_name='교재')),
            ],
            options={
                'verbose_name': '성적 분석',
                'verbose_name_plural': '성적 분석',
            },
        ),
        migrations.CreateModel(
            name='QuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='정답 여부')),
                ('grade_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.gradeanalysis', verbose_name='성적 분석')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textbooks.textbookquestion', verbose_name='문제')),
            ],
            options={
                'verbose_name': '문제 결과',
                'verbose_name_plural': '문제 결과',
            },
        ),
    ]
