# Generated by Django 4.2.16 on 2024-11-15 01:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0007_remove_book_entry_date_remove_book_purchase_location'),
        ('students', '0007_student_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='수량')),
                ('list_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='정가')),
                ('unit_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='단가')),
                ('selling_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='판매가')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('received_date', models.DateField(default=django.utils.timezone.now, verbose_name='입고일')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='도서명')),
            ],
            options={
                'verbose_name': '도서 재고',
                'verbose_name_plural': '도서 재고',
                'ordering': ['-received_date', 'book__name'],
            },
        ),
        migrations.CreateModel(
            name='BookDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_date', models.DateField(default=django.utils.timezone.now, verbose_name='판매일')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='수량')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('book_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.bookstock', verbose_name='도서')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '도서 판매',
                'verbose_name_plural': '도서 판매',
                'ordering': ['-sold_date', 'book_stock__book__name'],
            },
        ),
    ]
