# Generated by Django 4.2.16 on 2024-11-15 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdistribution',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='판매 수량'),
        ),
        migrations.AlterField(
            model_name='bookstock',
            name='received_date',
            field=models.DateField(verbose_name='입고일'),
        ),
    ]
