# Generated by Django 4.2.16 on 2024-11-21 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_alter_bookissue_issued_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='반품 수량')),
                ('return_date', models.DateField(verbose_name='반품 날짜')),
                ('book_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.bookstock', verbose_name='재고')),
            ],
            options={
                'verbose_name': '도서 반품',
                'verbose_name_plural': '도서 반품 목록',
            },
        ),
    ]
