# Generated by Django 5.1 on 2024-10-24 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='호실')),
                ('date', models.DateField(verbose_name='부과년월')),
                ('charge', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='부과금액')),
                ('date_paid', models.DateField(blank=True, null=True, verbose_name='납부일자')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '관리비',
                'verbose_name_plural': '관리비',
                'ordering': ['-date', 'room'],
                'indexes': [models.Index(fields=['room'], name='maintenance_room_436bc4_idx'), models.Index(fields=['date'], name='maintenance_date_be465d_idx'), models.Index(fields=['date_paid'], name='maintenance_date_pa_52f6be_idx')],
            },
        ),
    ]
