# Generated by Django 5.1 on 2024-10-24 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-date', 'room'], 'verbose_name': '관리비', 'verbose_name_plural': '관리비 목록'},
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='charge',
            field=models.IntegerField(help_text='0 이상의 금액을 입력해주세요.', validators=[django.core.validators.MinValueValidator(0, message='금액은 0 이상이어야 합니다.')], verbose_name='부과금액'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(help_text='년월을 선택해주세요.', verbose_name='부과년월'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='room',
            field=models.IntegerField(help_text='양수만 입력 가능합니다.', validators=[django.core.validators.MinValueValidator(1, message='호실 번호는 양수여야 합니다.')], verbose_name='호실'),
        ),
    ]
