# Generated by Django 5.1 on 2024-10-24 00:46

import maintenance.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenance_options_alter_maintenance_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=maintenance.models.MonthYearField(help_text='년월을 선택해주세요 (예: 2024년 10월)', verbose_name='부과년월'),
        ),
    ]
