# Generated by Django 5.1 on 2024-10-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_maintenance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(help_text='년월을 선택해주세요 (예: 2024년 10월)', verbose_name='부과년월'),
        ),
    ]
