# Generated by Django 5.1 on 2024-10-13 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='수강료 기준 월')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='수강료')),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class', verbose_name='수업')),
            ],
            options={
                'verbose_name': '수강료',
                'verbose_name_plural': '수강료',
                'unique_together': {('class_instance', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TuitionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='납부 금액')),
                ('payment_date', models.DateField(verbose_name='납부일')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='학생')),
                ('tuition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.tuition', verbose_name='수강료')),
            ],
            options={
                'verbose_name': '수강료 납부',
                'verbose_name_plural': '수강료 납부',
            },
        ),
    ]
